-- Схема программы лояльности. Скрипт идемпотентен: выполняется при каждом запуске.

CREATE TABLE IF NOT EXISTS customer (
    customer_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name    VARCHAR(200) NOT NULL,
    phone        VARCHAR(20)  NOT NULL UNIQUE,
    email        VARCHAR(200),
    birth_date   DATE,
    created_at   TIMESTAMP    NOT NULL DEFAULT now(),
    status       VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'BLOCKED'))
);

CREATE TABLE IF NOT EXISTS loyalty_account (
    account_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  INTEGER       NOT NULL REFERENCES customer (customer_id),
    card_number  VARCHAR(32)   NOT NULL UNIQUE,
    balance      NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (balance >= 0),
    tier         VARCHAR(20)   NOT NULL DEFAULT 'BASE' CHECK (tier IN ('BASE', 'SILVER', 'GOLD')),
    status       VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'BLOCKED', 'CLOSED')),
    opened_at    TIMESTAMP     NOT NULL DEFAULT now(),
    updated_at   TIMESTAMP     NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_account_customer ON loyalty_account (customer_id);

CREATE TABLE IF NOT EXISTS source_operation (
    operation_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id     INTEGER       NOT NULL REFERENCES customer (customer_id),
    operation_type  VARCHAR(30)   NOT NULL CHECK (operation_type IN ('PURCHASE')),
    external_id     VARCHAR(64)   UNIQUE,
    amount          NUMERIC(14,2) NOT NULL CHECK (amount > 0),
    operation_date  TIMESTAMP     NOT NULL DEFAULT now(),
    store_code      VARCHAR(32)
);
CREATE INDEX IF NOT EXISTS ix_operation_customer ON source_operation (customer_id);

-- rule_type: PERCENT | FIXED | PER_100 (см. AccrualCalculatorRegistry); без CHECK,
-- чтобы новый тип правила добавлялся только кодом, без миграции схемы.
-- category: уровень счёта (BASE/SILVER/GOLD), к которому применяется правило; NULL = ко всем.
CREATE TABLE IF NOT EXISTS accrual_rule (
    rule_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200)  NOT NULL,
    rule_type   VARCHAR(30)   NOT NULL,
    value       NUMERIC(14,4) NOT NULL CHECK (value >= 0),
    category    VARCHAR(50),
    valid_from  TIMESTAMP     NOT NULL DEFAULT now(),
    valid_to    TIMESTAMP,
    is_active   BOOLEAN       NOT NULL DEFAULT TRUE,
    CHECK (valid_to IS NULL OR valid_to > valid_from)
);

-- expire_days: сколько дней заявка на списание может ожидать подтверждения.
CREATE TABLE IF NOT EXISTS redemption_rule (
    rule_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(200)  NOT NULL,
    max_percent  NUMERIC(5,2)  NOT NULL CHECK (max_percent > 0 AND max_percent <= 100),
    min_amount   NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (min_amount >= 0),
    max_amount   NUMERIC(14,2) CHECK (max_amount IS NULL OR max_amount > 0),
    expire_days  INTEGER       NOT NULL DEFAULT 1 CHECK (expire_days > 0),
    is_active    BOOLEAN       NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS accrual_request (
    request_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id    INTEGER       NOT NULL REFERENCES loyalty_account (account_id),
    customer_id   INTEGER       NOT NULL REFERENCES customer (customer_id),
    rule_id       INTEGER       REFERENCES accrual_rule (rule_id),
    operation_id  INTEGER       NOT NULL REFERENCES source_operation (operation_id),
    bonus_amount  NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (bonus_amount >= 0),
    status        VARCHAR(20)   NOT NULL
                  CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'EXPIRED')),
    created_at    TIMESTAMP     NOT NULL DEFAULT now(),
    processed_at  TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_accrual_request_account ON accrual_request (account_id);

CREATE TABLE IF NOT EXISTS redemption_request (
    request_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id    INTEGER       NOT NULL REFERENCES loyalty_account (account_id),
    customer_id   INTEGER       NOT NULL REFERENCES customer (customer_id),
    rule_id       INTEGER       NOT NULL REFERENCES redemption_rule (rule_id),
    operation_id  INTEGER       NOT NULL REFERENCES source_operation (operation_id),
    bonus_amount  NUMERIC(14,2) NOT NULL CHECK (bonus_amount > 0),
    status        VARCHAR(20)   NOT NULL
                  CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'EXPIRED')),
    created_at    TIMESTAMP     NOT NULL DEFAULT now(),
    processed_at  TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_redemption_request_account ON redemption_request (account_id);
CREATE INDEX IF NOT EXISTS ix_redemption_request_operation ON redemption_request (operation_id);

-- amount со знаком: начисление > 0, списание < 0.
CREATE TABLE IF NOT EXISTS bonus_transaction (
    transaction_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id             INTEGER       NOT NULL REFERENCES loyalty_account (account_id),
    accrual_request_id     INTEGER       UNIQUE REFERENCES accrual_request (request_id),
    redemption_request_id  INTEGER       UNIQUE REFERENCES redemption_request (request_id),
    transaction_type       VARCHAR(20)   NOT NULL CHECK (transaction_type IN ('ACCRUAL', 'REDEMPTION')),
    amount                 NUMERIC(14,2) NOT NULL,
    balance_after          NUMERIC(14,2) NOT NULL CHECK (balance_after >= 0),
    created_at             TIMESTAMP     NOT NULL DEFAULT now(),
    CHECK (num_nonnulls(accrual_request_id, redemption_request_id) <= 1),
    CHECK ((transaction_type = 'ACCRUAL' AND amount > 0) OR (transaction_type = 'REDEMPTION' AND amount < 0))
);
CREATE INDEX IF NOT EXISTS ix_transaction_account ON bonus_transaction (account_id);
